### ISSUE TITLE
ag-theme-astro class is missing and results in broken ag-grids

### ISSUE THREAD

**Issue by run2xs** [RocketCommunicationsInc/astro-components-stencil#156]
Atlas currently depends on the class, ag-theme-astro, to style its ag-grids (v25.2).  That css class used to be found in astro-theme.scss, but it does not appear to exist in the astro-web-components package (0.0.12).

As a workaround for now, I'm going to add that file back to our shared Astro library, but ideally we will use something from astro-web-components in the future.

**Comment by markacianfrani** [comment]
We've created a separate standalone package for the ag grid theme over at https://github.com/RocketCommunicationsInc/ag-grid-theme that uses the new stencil css custom props. Let us know if you run into any issues installing that. We'll have documentation shortly in our storybook, but in the meantime you can checkout the readme in that repo

**Comment by run2xs** [comment]
Hi Mark,

I'm getting a 404 when I go to that link.

Thanks,
Kevin

**Comment by markacianfrani** [comment]
@run2xs sorry about that! we had it set to private. you should be good now

**Comment by run2xs** [comment]
I sent you an email on this but also wanted to update here.  I tested it this morning, and it looks good.  Thanks!
