### ISSUE TITLE
Cherry-picking icons does not seem to work

### ISSUE THREAD

**Issue by JamesTann** [RocketCommunicationsInc/astro-components-stencil#253]
I am trying to import and define select icons like so:

```
import { RuxIcon } from "@astrouxds/astro-web-components/dist/components/rux-icon";
import { RuxIconFolder } from "@astrouxds/astro-web-components/dist/components/rux-icon-folder";

customElements.define("rux-icon", RuxIcon);
customElements.define("rux-icon-folder", RuxIconFolder);
```

However, using this method with icons causes the icons to disappear. These components were functioning fine when I was using the lazy loader to define all the web components.

The icons render in the DOM but are not visible see this example:

```
<rux-button @click="selectFile()"><rux-icon-folder />Upload</rux-button>
```
![image](https://user-images.githubusercontent.com/48925605/135299941-b4012042-125f-4e72-9929-5a8536ab2948.png)

The folder icon is present in the DOM:

![image](https://user-images.githubusercontent.com/48925605/135300136-cf940562-00dc-4cda-8f14-b6bd1bc9baba.png)

I am trying to follow the Astro docs [here](https://astro-stencil.netlify.app/?path=/docs/components-icons--all-icons#cherry-picking).

**Comment by JamesTann** [comment]
I am also facing a similar issue with the Log component. It is not rendering properly:

![image](https://user-images.githubusercontent.com/48925605/135301212-34e4419e-e505-4556-ae3e-071c47775913.png)

The [docs](https://astro-stencil.netlify.app/?path=/docs/components-log--log#cherry-picking) only say it depends on Icon, Button, and ButtonGroup.

**Comment by markacianfrani** [comment]
You'll still want to use the rux-icon wrapper for the icon like so:

```
<rux-button @click="selectFile()"><rux-icon icon="folder"></rux-icon>Upload</rux-button>
```

Also make sure not to use self-closing tags (an annoying limitation of web components)

https://codesandbox.io/s/compassionate-mclaren-ws7dp?file=/src/App.vue

For the Log, that's actually a typo on our end. sorry about that! The correct dependencies are:

```
import { RuxTable } from "@astrouxds/astro-web-components/dist/components/rux-table";
import { RuxTableHeader } from "@astrouxds/astro-web-components/dist/components/rux-table-header";
import { RuxTableHeaderRow } from "@astrouxds/astro-web-components/dist/components/rux-table-header-row";
import { RuxTableHeaderCell } from "@astrouxds/astro-web-components/dist/components/rux-table-header-cell";
import { RuxInput } from "@astrouxds/astro-web-components/dist/components/rux-input";
import { RuxTableBody } from "@astrouxds/astro-web-components/dist/components/rux-table-body";
import { RuxTableRow } from "@astrouxds/astro-web-components/dist/components/rux-table-row";
import { RuxTableCell } from "@astrouxds/astro-web-components/dist/components/rux-table-cell";
import { RuxDatetime } from "@astrouxds/astro-web-components/dist/components/rux-datetime";


customElements.define('rux-table', RuxTable)
customElements.define('rux-table-header', RuxTableHeader)
customElements.define('rux-table-header-row', RuxTableHeaderRow)
customElements.define('rux-table-header-cell', RuxTableHeaderCell)
customElements.define('rux-input', RuxInput)
customElements.define('rux-table-body', RuxTableBody)
customElements.define('rux-table-row', RuxTableRow)
customElements.define('rux-table-cell', RuxTableCell)
customElements.define('rux-datetime', RuxDatetime)
```

(it's on our roadmap to have components autoload their dependencies to avoid this monstrosity)

**Comment by JamesTann** [comment]
Thank you for the response! I will switch back to using the normal rux-icon.
